### ISSUE TITLE
[design] 공통UI 파트3 화면개발

### ISSUE THREAD

**Issue by sypear** [daengnyang-market/daengnyang-market-client#10]
## 작업할 내용 간략한 설명
- 공통UI 중 파트3 Search, Follow, TextInput, Alert, HiddenMenuList 컴포넌트 개발 예정입니다.

## 구현 방법 및 예상 화면
![스크린샷 2022-12-11 오전 10 38 13](https://user-images.githubusercontent.com/105365737/206882503-b4bcc198-ae91-4ce2-b223-0a55e4339540.png)

**Comment by rosamondkim** [comment]
승연님 화이팅!
