### ISSUE TITLE
[design] ProductCarousel 캐러셀 컴포넌트 구현

### ISSUE THREAD

**Issue by rosamondkim** [daengnyang-market/daengnyang-market-client#102]
## 작업할 내용 간략한 설명
- YourProfile 페이지에 넣을 Product 영역을 캐러셀 라이브러리 사용해서 구현할 예정입니다.

## 구현 방법 및 예상 화면
<img width="388" alt="image" src="https://user-images.githubusercontent.com/96304623/207752245-63a630fe-edcc-4378-b219-fdc2597a793f.png">
- swiper 라이브러리를 이용해 구현할 예정입니다.

**Comment by sypear** [comment]
좋아요!! 그런데 캐러셀 안에 들어가는 내용이 상품이 꼭 아닐수도 있으니 파일명을 ProductCarousel가 아니라 조금 더 일반화하면 좋을거같아요! 흠...도트캐러셀..? ㅠㅠ..? 머가 좋을까.. 여튼 저도 그래서 제가 만든 캐러셀 파일명을 오토슬라이드캐러셀..? 뭐 이런거로 바꿔보려고 생각중입니다!
