### ISSUE TITLE
[design] 공통 UI 파트1 화면개발

### ISSUE THREAD

**Issue by euihokim** [daengnyang-market/daengnyang-market-client#12]
## 작업할 내용 간략한 설명
- 공통UI 중 파트1 Post, PostOnlyText, Product 컴포넌트 개발 예정입니다.

## 구현 방법 및 예상 화면
![image](https://user-images.githubusercontent.com/112460383/206891678-598cf745-0105-4304-b93c-9a7164e0cd4d.png)

**Comment by rosamondkim** [comment]
화이팅~~

**Comment by sypear** [comment]
의호님 파이팅!!
