### ISSUE TITLE
[add] 이미지를 전역으로 사용하기 위한 파일추가

### ISSUE THREAD

**Issue by yedol1** [daengnyang-market/daengnyang-market-client#13]
## 작업할 내용 간략한 설명
- 이미지들을 하나의 파일에 import 시켜서, 전역으로 사용하기 위해 파일을 추가합니다. 

## 구현 방법 및 예상 동작
- 이미지 파일을 불러오는 것에 있어, 간편해진다.

## 특이사항
- 없습니다.

**Comment by sypear** [comment]
광렬님 최고!

**Comment by rosamondkim** [comment]
광렬님 감사합니다 💓

**Comment by euihokim** [comment]
감사합니다!!
