### ISSUE TITLE
[design] MyProfile 과 UserProfile 구분하여 ProfileHeader 구성하기

### ISSUE THREAD

**Issue by rosamondkim** [daengnyang-market/daengnyang-market-client#132]
## 작업할 내용 간략한 설명
* My Profile 페이지 퍼블리싱 예정입니다.
* profilePage 폴더 내 ProfileHeader, ProfilePost, ProfileProduct 컴포넌트를 사용하여 작업할 계획입니다.
* ProfileHeader에 followState, profileState 값을 주어 각각 다르게 구성할 예정입니다.

## 구현 방법 및 예상 화면

![207893382-a4b5c0a0-2547-4e69-bb11-7d8550842d76](https://user-images.githubusercontent.com/96304623/208059811-7939127a-cce5-4ec3-94f5-d2413eb0c3f2.png)

**Comment by sypear** [comment]
민승님 파잇띵 🥺
