### ISSUE TITLE
[bug] URL 경로에 따라 상이한 Favicon

### ISSUE THREAD

**Issue by euihokim** [daengnyang-market/daengnyang-market-client#181]
## 버그 내용
- URL 경로가 한 depth 증가하면 Favicon이 나타나지 않음

## 재현 과정
![image](https://user-images.githubusercontent.com/112460383/208242345-9ae350b1-aee0-41a9-9785-b307f0984396.png)
![image](https://user-images.githubusercontent.com/112460383/208242302-066f6109-5846-491c-bd88-a383fd56a3a4.png)

## 기타
- 없음.

**Comment by sypear** [comment]
👍

**Comment by sypear** [comment]
제가 작업하겠습니다.

**Comment by euihokim** [comment]
> 제가 작업하겠습니다.

넵 확인했습니다! 감사합니다
