### ISSUE TITLE
[bug] 로컬스토리지에 토큰이 없을 때 401 에러가 발생하는 현상

### ISSUE THREAD

**Issue by sypear** [daengnyang-market/daengnyang-market-client#213]
## 버그 내용
- 로컬스토리지에 토큰이 없을 때 401 에러가 발생하는 현상

## 재현 과정
1. 로컬스토리지에 토큰이 없는 상태로 루트 경로('/')에 진입한다.

## 스크린샷
<img width="645" alt="스크린샷 2022-12-19 오후 8 04 52" src="https://user-images.githubusercontent.com/105365737/208413472-320604df-9349-4e8d-ac5b-c6d8cecce0c1.png">

## 기타
- 원인 : 토큰이 없을때 토큰 검증 로직이 실패해서 에러 발생
- 해결 : 예외처리 필요

**Comment by rosamondkim** [comment]
확인했습니다~ 흑흑 작업하겠습니다
