### ISSUE TITLE
[bug] 로그인 정보가 없는데도 로그인, 회원가입 이외 페이지에 접근이 되는 현상

### ISSUE THREAD

**Issue by sypear** [daengnyang-market/daengnyang-market-client#252]
## 버그 내용
- 로그인 정보가 없는데도 로그인, 회원가입 이외 페이지에 접근이 되는 현상

## 재현 과정
1. 로그인 정보가 없는 상태로 프로필, 커뮤니티, 채팅 등 페이지에 접근한다.

## 예상 해결 방법
- 원인 : 라우터에 리다이렉트 로직이 없음
- 해결 방법 : 라우터에 리다이렉트 로직 추가

## 기타
- **추후 진행 예정. 기록을 위해 미리 남겨둠**

**Comment by rosamondkim** [comment]
리다이렉트 로직.... 🤔
