### ISSUE TITLE
[design] 회원가입 메인화면 구성

### ISSUE THREAD

**Issue by yedol1** [daengnyang-market/daengnyang-market-client#27]
## 작업할 내용 간략한 설명
- 회원가입의 메인화면을 디자인 시안대로 구성할 예정입니다.

## 구현 방법 및 예상 화면
![회원가입 디자인](https://user-images.githubusercontent.com/57481378/207234265-b95d0ad0-57a6-4d2a-9663-9f5aba1a2192.png)

## 특이사항
- 현재까지 없습니다~!

**Comment by rosamondkim** [comment]
화이팅!!!! 시작이 좋네용 😃

**Comment by sypear** [comment]
🌸 파이팅 🌸
