### ISSUE TITLE
[bug] 사용자가 위치 정보를 허용하지 않았을 때 날씨 페이지에서 무한 로딩이 일어나는 현상

### ISSUE THREAD

**Issue by sypear** [daengnyang-market/daengnyang-market-client#281]
## 버그 내용
- 사용자가 위치 정보를 허용하지 않았을 때 무한 로딩이 일어나는 현상

## 재현 과정
1. 커뮤니티 날씨 페이지에 진입한다.
2. 위치 정보를 허용하지 않는다.

## 기타
- 예외처리 추가 필요
- 동물병원 기본 기능 구현 후 진행 예정

**Comment by euihokim** [comment]
승연님 이러다가 기상청 들어가시겠어요

**Comment by sypear** [comment]
> 승연님 이러다가 기상청 들어가시겠어요

ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

**Comment by rosamondkim** [comment]
API 마스터 승연님,,,,
