### ISSUE TITLE
[design] 시작 화면 퍼블리싱

### ISSUE THREAD

**Issue by rosamondkim** [daengnyang-market/daengnyang-market-client#29]
## 작업할 내용 간략한 설명
- 시작화면 마크업&스타일 시안대로 구성할 예정입니다.

## 구현 방법 및 예상 화면
<img width="265" alt="image" src="https://user-images.githubusercontent.com/96304623/207240843-f07a83f1-9e0d-4398-b293-45b8e54d6283.png">

**Comment by sypear** [comment]
🔥 파이팅 🔥
