### ISSUE TITLE
[bug] 회원가입 시 이미지 미적용에 따른 기본 프로필 이미지 설정 오류

### ISSUE THREAD

**Issue by euihokim** [daengnyang-market/daengnyang-market-client#291]
## 버그 내용
- #266
- 위와 같은 이슈를 해결했었으나, 로컬에서 등록된 이미지로 불러오기 때문에 다른 사용자들에게서는 이미지가 보이지 않음.

## 기타
- 기본 프로필용 계정을 서버에 하나 만들어서 이미지를 불러오는 식으로 작업해 볼 예정.

**Comment by sypear** [comment]
파이팅 ٩( ᐛ )و
