### ISSUE TITLE
[feat] ProfilePost  코드 리팩토링

### ISSUE THREAD

**Issue by rosamondkim** [daengnyang-market/daengnyang-market-client#318]
## 작업할 내용 간략한 설명
* useState 리스트형 앨범형 전환 버튼 리팩토링
```jsx
  const [listBtn, setListBtn] = useState(true);
  const [albumBtn, setAlbumBtn] = useState(false);
  const [listClicked, onListClicked] = useState(true);
  const [albumClicked, onAlbumClicked] = useState(false);
```
* 여러가지 이미지일때 레이어 아이콘 추가하기
<img width="490" alt="image" src="https://user-images.githubusercontent.com/96304623/209605149-06895835-f4eb-414d-8444-e2db40e22e4d.png">

**Comment by sypear** [comment]
♻️ 리팩토링 멋져요 ♻️
