### ISSUE TITLE
[bug] ProductProfile useEffect 로 서버 무한요청 보내지는 현상 해결

### ISSUE THREAD

**Issue by rosamondkim** [daengnyang-market/daengnyang-market-client#329]
## 버그 내용
- useEffect 두번째 요소 의존성 배열에 productList를 넣어서 서버에 무한요청 보내지는 현상 

## 버그 발생 환경
- Device: 모바일의 경우만 작성 [e.g. iPhone6]
- OS: [e.g. Windows, Mac, IOS, Android]
- Browser Version [e.g. 22]

**Comment by sypear** [comment]
오늘의 교훈 1 - useEffect와 통신 코드를 함께 쓸때는 아주 주의하자
오늘의 교훈 2 - 개리선생님 감사합니다 💪
