### ISSUE TITLE
[refactoring] 이미지 리사이징을 위한 ProductRegistrationPage.jsx 리팩토링

### ISSUE THREAD

**Issue by euihokim** [daengnyang-market/daengnyang-market-client#352]
## 작업할 내용 간략한 설명
- 이미지 리사이징을 위한 ProductRegistrationPage.jsx 리팩토링을 진행하고자 합니다.

## 구현 방법 및 예상 동작
- 라이브러리를 활용해 용량이 큰 이미지도 업로드 가능하게 수정됩니다.

## 특이사항
- 없습니다.

**Comment by sypear** [comment]
멋져요 ~
