### ISSUE TITLE
[bug] 사용자의 프로필 피드 게시물이 10개까지밖에 보이지 않는 현상

### ISSUE THREAD

**Issue by rosamondkim** [daengnyang-market/daengnyang-market-client#397]
## 버그 내용
- 사용자의 프로필 피드 게시물이 10개까지밖에 보이지 않는 현상 

## 재현 과정
1. 홈 피드에서 사용한 `react-intersection-observer` 사용할 예정.

## 우려 사항
- 이전처럼  바닥에 닿으면 무한 요청 보내는 현상을 고려하여 done 함수 추가해주는 것 잊지 말기

## 버그 발생 환경
- Device: 모바일의 경우만 작성 [e.g. iPhone6]
- OS: [e.g. Windows, Mac, IOS, Android]
- Browser Version [e.g. 22]

**Comment by sypear** [comment]
무한스크롤에 빠져버린 me & 민승.. 🥹
