### ISSUE TITLE
[design] Your Profile 페이지 퍼블리싱

### ISSUE THREAD

**Issue by rosamondkim** [daengnyang-market/daengnyang-market-client#64]
## 작업할 내용 간략한 설명
- your Profile 페이지 퍼블리싱 예정입니다.
- 갤러리형, 앨범형 두가지로 구현할 예정입니다. 
- 이미지가 없는 게시글일 경우 앨범형에선 띄우지 않게 작업 예정입니다.
- 상품 있는 경우에만 상품 섹션 가로 스크롤바로 구현할 예정입니다.

## 예상 화면
<img width="824" alt="image" src="https://user-images.githubusercontent.com/96304623/207473523-27b5c438-573e-4f28-adb1-dab3e6d243cc.png">

## 특이사항
- 시간이 소요될 것으로 예상합니다.

**Comment by sypear** [comment]
고난이도 페이지군요...🥺 민승님 파이팅!!
