### ISSUE TITLE
[design] 게시물 상세 페이지 퍼블리싱

### ISSUE THREAD

**Issue by yedol1** [daengnyang-market/daengnyang-market-client#78]
## 작업할 내용 간략한 설명
- 게시물 상세 페이지를 전반적으로 퍼블리싱 할것 입니다.

## 구현 방법 및 예상 화면
![PostDetailPage](https://user-images.githubusercontent.com/57481378/207512043-0b8a94da-5782-4a7d-b700-516f2cb291a2.png)

## 특이사항
- 없습니다~!

**Comment by sypear** [comment]
저희 공통UI에는 없는 댓글 컴포넌트도 만드셔야하는군요... 광렬님 파이팅🔥
