### ISSUE TITLE
[assets] 커뮤니티 페이지 캐러셀 구현을 위한 이미지 에셋 추가

### ISSUE THREAD

**Issue by sypear** [daengnyang-market/daengnyang-market-client#85]
## 작업할 내용 간략한 설명
- 커뮤니티 페이지 캐러셀 구현을 위해 광고 이미지를 3장 추가할 예정입니다.

## 구현 방법 및 예상 동작
- 이미지 3장 추가
- CommonImages.jsx 파일에 내용 갱신

## 특이사항
- 없습니다.

**Comment by rosamondkim** [comment]
정말 신기하네요...
